// <auto-generated />
namespace Store.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Products : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Products));
        
        string IMigrationMetadata.Id
        {
            get { return "201309260813229_Products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
